- name: Create docker postgres directory
  file:
    path: "{{ user.home }}/docker/docker_postgres"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy Dockerfile
  copy:
    src: ./Dockerfile
    dest: "{{ user.home }}/docker/docker_postgres/Dockerfile"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
